version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DEBUG=1
      - DATABASE_NAME=mydb
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=12345678
      - DATABASE_HOST=db  # Reference the PostgreSQL service
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/usr/src/app/entrypoint.sh"]

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydb"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
