# Generated by Django 5.1.5 on 2025-01-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
