# Generated by Django 5.1.5 on 2025-01-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='thumbnail_image',
        ),
    ]
