# Generated by Django 5.1.5 on 2025-01-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_image_product_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_image',
        ),
    ]
