# Generated by Django 5.1.5 on 2025-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_user_alter_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='defaultusername', max_length=255),
        ),
    ]
