# Generated by Django 5.1.5 on 2025-01-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0013_alter_customer_options_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='specific_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='store_customers_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='store_customers_permissions', to='auth.permission'),
        ),
    ]
